const productsData = [
  {
    id: "1",
    img: "./myimages/terracotta_Pots.jpg",
    name: "Terracotta Pot",
    colour: "Natural",
    material: "Made in England",
    description: "Saucer not included",
    price: 3,
  },
  {
    id: "2",
    img: "./myimages/plant-signpost.jpg",
    name: "Plant signposts",
    price: 5,
    colour: "White",
    material: "Compostable plastic",
    description: "Pack of 10",
  },
  {
    id: "3",
    img: "./myimages/camping_mug.jpg",
    name: "Coffee Mug",
    price: 8,
    colour: "White",
    material: "Enamel metal",
    description: "Handwash only",
  },
  {
    id: "4",
    name: "Baseball Cap",
    img: "./myimages/green_cap.jpg",
    price: 12,
    colour: "Green",
    material: "Synthetic",
    description: "Logo on front",
  },
  {
    id: "5",
    name: "T-Shirt",
    img: "./myimages/t-short.jpg",
    price: 10,
    colour: "White",
    material: "100% cotton",
    description: "Logo on front",
  },
  {
    id: "6",
    name: "Gardener Apron",
    img: "./myimages/gardener_Apron.jpg",
    price: 20,
    colour: "Royal blue",
    material: "100% cotton",
    description: "Logo on front",
  },
];

export default productsData;
